import pickle
import numpy as np
from scipy.stats import pearsonr, kendalltau

# 1. Path to your model's output (the predictions)
PREDICTIONS_PATH = "/home/eduard/Desktop/Research/Adrian/VQPP/VAST/corelation_cnn_datasets/test_predictions.pickle"

# 2. Path to the TEST dataset generated by the previous script
# We need this because it contains the GT scores in the correct order
TEST_DATASET_PATH = "/home/eduard/Desktop/Research/Adrian/VQPP/VAST/corelation_cnn_datasets/msrvtt_test_rec.pickle"

def load_predictions(path):
    with open(path, "rb") as f:
        return pickle.load(f)

def load_ground_truth_from_sequential(path):
    gt_scores = []
    with open(path, "rb") as f:
        while True:
            try:
                # Each item is (matrix, score)
                _, score = pickle.load(f)
                gt_scores.append(score)
            except EOFError:
                break
    return gt_scores

def compute_correlations(preds, gts, title):
    # Ensure they are the same length
    if len(preds) != len(gts):
        print(f"Warning: Length mismatch! Preds: {len(preds)}, GTs: {len(gts)}")
        # Trim to the smaller length if necessary
        min_len = min(len(preds), len(gts))
        preds, gts = preds[:min_len], gts[:min_len]

    pearson, p_pearson = pearsonr(preds, gts)
    kendall, p_kendall = kendalltau(preds, gts)

    print(f"--- {title} ---")
    print(f"Pearson Correlation: {pearson} (p-value: {p_pearson})")
    print(f"Kendall Correlation: {kendall} (p-value: {p_kendall})")
    print("-" * (len(title) + 8))

# --- EXECUTION ---
if __name__ == "__main__":
    print("Loading data...")
    y_pred = load_predictions(PREDICTIONS_PATH)
    y_true = load_ground_truth_from_sequential(TEST_DATASET_PATH)

    compute_correlations(y_pred, y_true, "CNN Regressor Performance")